# Generated by Django 4.0.3 on 2022-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(default='img/favicon.png', upload_to='')),
                ('site_title', models.CharField(max_length=100)),
                ('name_surname', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('home_background', models.ImageField(default='img/favicon.png', upload_to='')),
                ('twitter_url', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
                ('skype_url', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('calender_url', models.CharField(max_length=100)),
            ],
        ),
    ]
