# Generated by Django 4.0.3 on 2022-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='favicon',
            field=models.ImageField(default='img/favicon.png', upload_to='img/favicon/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_background',
            field=models.ImageField(default='img/favicon.png', upload_to='img/background/'),
        ),
    ]
