# Generated by Django 4.0.3 on 2022-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_favicon_alter_home_home_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='username',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
