# Generated by Django 4.0.3 on 2022-08-13 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='calender_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='skype_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL.', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
    ]
